### ISSUE TITLE
Question about repetitive line

### ISSUE THREAD

**Issue by kevinszuchet** [lmammino/dotfiles#1]
Hi,
First of all, thanks for this repo, it is so useful and simple to understand.

My doubt is why is necessary to repeat this line that was included before on the .bashrc file?
https://github.com/lmammino/dotfiles/blob/f7c15d1ec7219583192851512e633b3ae52da90a/.bash_profile#L17

Thanks again!

**Comment by lmammino** [comment]
Hey @kevinszuchet, good point! That's an unnecessary repetition. I'll have it fixed :)
Thanks for reporting this!
